---

- name: Install Go
  yum:
    name: golang
    state: latest
  become: yes

- name: Download the proxy
  get_url:
    url: https://github.com/abutaha/aws-es-proxy/releases/download/v0.4/aws-es-proxy-0.4-linux-amd64
    dest: /opt/aws-es-proxy
    mode: 755
  become: yes

- name: Put the AWS ES proxy in the bin path
  file:
    state: link
    src: /opt/aws-es-proxy
    dest: /usr/bin/aws-es-proxy
  become: yes

