---

- name: Install PPA repos
  apt_repository:
    repo: ppa:masterminds/glide
    update_cache: yes
  become: yes

- name: Install go
  apt:
    name: "{{ item }}"
  with_items:
    - golang-go
    - glide
  become: yes
